alias 0='~/.config'
alias 00='~/dev'
alias 1='cd /mnt/storage1/Movies'
alias 2='cd /mnt/storage1/'
alias 3='cd /mnt/storage1/TV_shows'
alias 4='cd /mnt/storage1/tmp_extractions'
alias monitor='inotifywait -m -r -e modify,create,delete /mnt/storage1/ | while read -r line; do printf "\033[2K\r$line"; done'
